// Copyright (c) 2026 PXA Network. Part of PXA; distributed under the repository's licence (see LICENSE).
//
// examples/server/pxa-explain.h is the pure, header-only layer behind `GET /pxa/explain` and the
// `/pxa` page (showcase lane, 2026-09-25): it must never touch a device or the decode path, so
// this test exercises it exactly as a CPU-only unit -- no GPU, no server, no model file. It covers
// the three things a page consumer (or a future lane) can rely on:
//   1. pxa_explain_card_entry(): the VRAM arithmetic (used = total - free, byte -> MiB) is right.
//   2. pxa_explain_levers_json(): a lever whose environment value differs from its catalog default
//      shows up under "user_set" with both values; a default-on lever left alone shows up under
//      "default_on"; the counts match the catalog. Uses the live catalog (pxa_lever_catalog()),
//      not a fixture, so it stays true if the catalog grows -- like test-pxa-autoconfig.cpp, it
//      picks its test row (a "default-on" one and a diagnostic one, PXA_EXPLAIN, whose default is
//      known: "off") straight out of the table, not from a hand-maintained copy.
//   3. pxa_explain_build(): the merged /pxa/explain object carries every top-level key both halves
//      contribute -- pxa_autoconfig_json()'s own (schema/level/topology/model/picks/env/ts_even/
//      levers_declared) and this file's (engine/model_alias/cards/levers/live) -- so a schema
//      regression (a dropped key) fails here instead of in a browser.

#include "pxa-explain.h"
#include "pxa-registry.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

static int g_fail = 0;

#define CHECK(cond, msg) do { \
        if (!(cond)) { \
            printf("FAIL %s:%d: %s\n", __func__, __LINE__, msg); \
            g_fail++; \
        } \
    } while (0)

static void test_card_entry() {
    // 16 GiB total, 1 GiB free -> 15 GiB used, everything in MiB.
    const size_t total = 16ull * 1024 * 1024 * 1024;
    const size_t free_ = 1ull * 1024 * 1024 * 1024;
    const auto j = pxa_explain_card_entry(0, "Tesla P100-PCIE-16GB", 60, free_, total);
    CHECK(j.at("index").get<int>() == 0, "index");
    CHECK(j.at("name").get<std::string>() == "Tesla P100-PCIE-16GB", "name");
    CHECK(j.at("sm").get<int>() == 60, "sm");
    CHECK(j.at("vram_total_mib").get<uint64_t>() == 16384, "vram_total_mib");
    CHECK(j.at("vram_free_mib").get<uint64_t>()  == 1024,  "vram_free_mib");
    CHECK(j.at("vram_used_mib").get<uint64_t>()  == 15360, "vram_used_mib");

    // free > total (a transient racy read) must not underflow -- used clamps to 0, not a huge
    // unsigned wraparound. This function must never crash or lie in a way that renders as a
    // negative-looking VRAM bar on the page.
    const auto j2 = pxa_explain_card_entry(1, "weird", 70, total, free_);
    CHECK(j2.at("vram_used_mib").get<uint64_t>() == 0, "vram_used_mib clamps, does not underflow");
    printf("test_card_entry: %s\n", g_fail == 0 ? "PASS" : "FAIL so far");
}

static void test_levers_json() {
    size_t n = 0;
    const pxa_lever_decl * cat = pxa_lever_catalog(&n);
    CHECK(n > 0, "catalog is non-empty (generated by scripts/pxa-lever-catalog.py)");

    // PXA_EXPLAIN itself is always in the catalog (this very page's own diagnostic lever) with a
    // known default of "off" -- use it as the "user set it away from default" case.
    const pxa_lever_decl * expl = pxa_lever_find("PXA_EXPLAIN");
    CHECK(expl != nullptr, "PXA_EXPLAIN is a declared lever");
    if (expl) {
        CHECK(strcmp(expl->deflt, "off") == 0, "PXA_EXPLAIN default is \"off\" (test assumption)");
    }
    // Find one default-on row to use as the "left alone" case.
    const pxa_lever_decl * on_row = nullptr;
    for (size_t i = 0; i < n; ++i) {
        if (strcmp(cat[i].status, "default-on") == 0) { on_row = &cat[i]; break; }
    }
    CHECK(on_row != nullptr, "at least one default-on lever exists");

    unsetenv("PXA_EXPLAIN");
    if (on_row) unsetenv(on_row->name);
    {
        const auto j = pxa_explain_levers_json();
        CHECK(j.at("declared").get<size_t>() == n, "declared == catalog size");
        bool saw_explain_in_user_set = false;
        for (const auto & u : j.at("user_set")) {
            if (u.at("name").get<std::string>() == "PXA_EXPLAIN") saw_explain_in_user_set = true;
        }
        CHECK(!saw_explain_in_user_set, "unset PXA_EXPLAIN is not in user_set");
        if (on_row) {
            bool saw_on = false;
            for (const auto & e : j.at("default_on")) {
                if (e.at("name").get<std::string>() == on_row->name) saw_on = true;
            }
            CHECK(saw_on, "an untouched default-on lever appears in default_on");
        }
    }

    setenv("PXA_EXPLAIN", "1", 1);
    {
        const auto j = pxa_explain_levers_json();
        bool found = false;
        for (const auto & u : j.at("user_set")) {
            if (u.at("name").get<std::string>() == "PXA_EXPLAIN") {
                found = true;
                CHECK(u.at("value").get<std::string>() == "1", "user_set value reflects the env");
                CHECK(u.at("default").get<std::string>() == "off", "user_set carries the catalog default too");
            }
        }
        CHECK(found, "PXA_EXPLAIN=1 shows up under user_set once set");
    }
    unsetenv("PXA_EXPLAIN");
    printf("test_levers_json: %s\n", g_fail == 0 ? "PASS" : "FAIL so far");
}

static void test_build_schema() {
    // A synthetic pxa-autoconfig/1 object, built the same way test-pxa-autoconfig.cpp does (pure,
    // no GPU, no model file), so this test does not depend on a real boot either.
    pxa_model_info m;
    m.ok = true; m.arch = "qwen35"; m.tier = "PXQ4"; m.n_expert = 0; m.n_head_kv = 4; m.n_layer = 64;
    const pxa_topology t = pxa_topology_parse("2x600");
    const pxa_user_set u;
    const pxa_autoconfig ac = pxa_autoconfig_resolve(t, m, u, /*level=*/2, /*posture=*/0);
    const std::string autoconfig_json = pxa_autoconfig_json(t, m, ac, 2);

    nlohmann::ordered_json cards = nlohmann::ordered_json::array();
    cards.push_back(pxa_explain_card_entry(0, "Tesla P100-PCIE-16GB", 60, 1ull << 30, 16ull << 30));
    cards.push_back(pxa_explain_card_entry(1, "Tesla P100-PCIE-16GB", 60, 2ull << 30, 16ull << 30));

    nlohmann::ordered_json live;
    live["decode_tok_s"] = 23.4;
    live["prefill_tok_s"] = 812.0;
    live["speculative"] = { {"n_draft_total", 100}, {"n_draft_accepted", 63}, {"accept_rate", 0.63} };

    const std::string out = pxa_explain_build(autoconfig_json, cards, live, 4242, "deadbee",
                                              "Qwen3.8-27B-PXQ-mix27");
    const auto j = nlohmann::ordered_json::parse(out, nullptr, false);
    CHECK(!j.is_discarded(), "pxa_explain_build() output parses as JSON");
    if (j.is_discarded()) { printf("test_build_schema: FAIL (unparsable)\n"); return; }

    // pxa_autoconfig_json()'s own keys must survive the merge untouched.
    for (const char * k : {"level", "topology", "model", "picks", "env", "ts_even", "levers_declared"}) {
        CHECK(j.contains(k), (std::string("merged object still has \"") + k + "\"").c_str());
    }
    // and this file's own additions.
    for (const char * k : {"schema", "engine", "model_alias", "cards", "levers", "live"}) {
        CHECK(j.contains(k), (std::string("merged object has \"") + k + "\"").c_str());
    }
    CHECK(j.at("schema").get<std::string>() == "pxa-explain/1", "schema tag");
    CHECK(j.at("cards").size() == 2, "both cards made it through");
    CHECK(j.at("engine").at("build").get<int>() == 4242, "engine.build");
    CHECK(j.at("engine").at("commit").get<std::string>() == "deadbee", "engine.commit");
    CHECK(j.at("model_alias").get<std::string>() == "Qwen3.8-27B-PXQ-mix27", "model_alias");
    CHECK(j.at("live").at("decode_tok_s").get<double>() == 23.4, "live.decode_tok_s round-trips");
    CHECK(j.at("levers").contains("declared"), "levers sub-object is the full breakdown, not a stub");
    printf("test_build_schema: %s\n", g_fail == 0 ? "PASS" : "FAIL so far");
}

int main() {
    test_card_entry();
    test_levers_json();
    test_build_schema();
    if (g_fail) {
        printf("test-pxa-explain: %d check(s) FAILED\n", g_fail);
        return 1;
    }
    printf("test-pxa-explain: all checks PASSED\n");
    return 0;
}
