#pragma once

#include "llama.h"
#include "llama-grammar.h"
#include "reasoning-budget.h"
#include "pxa-spec-sampled.h"
#include <set>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>

#define A_DOT_B(a, b) a.b

// sampler types
enum class llama_sampler_type : char {
    DRY         = 'd',
    TOP_K       = 'k',
    TOP_P       = 'p',
    MIN_P       = 'm',
    TFS_Z       = 'f',
    XTC         = 'x',
    TOP_N_SIGMA = 'n',
    TYPICAL_P   = 'y',
    TEMPERATURE = 't',
    ADAPTIVE_P  = 'w',
    DIST     = 's',
};

enum common_grammar_trigger_type {
    COMMON_GRAMMAR_TRIGGER_TYPE_TOKEN,
    COMMON_GRAMMAR_TRIGGER_TYPE_WORD,
    COMMON_GRAMMAR_TRIGGER_TYPE_PATTERN,
    COMMON_GRAMMAR_TRIGGER_TYPE_PATTERN_FULL,
};

struct common_grammar_trigger {
    common_grammar_trigger_type type;
    std::string value;
    llama_token token = LLAMA_TOKEN_NULL;

    // T can only be nlohmann::ordered_json
    template <class T> T to_json() const;
    template <class T> static common_grammar_trigger from_json(const T& in);
};


// Grammar type enumeration
enum common_grammar_type {
    COMMON_GRAMMAR_TYPE_NONE,           // no grammar set
    COMMON_GRAMMAR_TYPE_USER,           // user-provided GBNF (--grammar / "grammar" API field)
    COMMON_GRAMMAR_TYPE_OUTPUT_FORMAT,  // auto-generated from JSON schema (--json-schema / "json_schema" API field)
    COMMON_GRAMMAR_TYPE_TOOL_CALLS,     // auto-generated by chat template parser for function calling
};

// Grammar variant struct with type and grammar string
struct common_grammar {
    common_grammar_type type = COMMON_GRAMMAR_TYPE_NONE;
    std::string grammar;

    // Default constructor - no grammar
    common_grammar() = default;

    // Constructor with type and grammar string
    common_grammar(common_grammar_type t, std::string g) : type(t), grammar(std::move(g)) {
        GGML_ASSERT(type != COMMON_GRAMMAR_TYPE_NONE || !grammar.empty());
    }

    // Check if a grammar is set
    bool empty() const { return type == COMMON_GRAMMAR_TYPE_NONE || grammar.empty(); }
};

// Returns the raw grammar string, or empty string if no grammar is set.
inline const std::string & common_grammar_value(const common_grammar & g) {
    return g.grammar;
}

// Returns true when the generation_prompt should be prefilled into the grammar sampler.
// Only output-format and tool-call grammars need prefill; user-supplied grammars must not be prefilled.
inline bool common_grammar_needs_prefill(const common_grammar & g) {
    return g.type == COMMON_GRAMMAR_TYPE_OUTPUT_FORMAT
        || g.type == COMMON_GRAMMAR_TYPE_TOOL_CALLS;
}


#define X_COMMON_PARAMS_SAMPLING                                 /*  \
    */  X( int32_t , min_keep            , 0     , std::round )  /*  0 = disabled, otherwise samplers should return at least min_keep tokens \
    */  X( int32_t , top_k               , 40    , std::round )  /*  <= 0 to use vocab size \
    */  X( float   , top_p               , 0.95f ,            )  /*  1.0 = disabled \
    */  X( float   , min_p               , 0.05f ,            )  /*  0.0 = disabled \
    */  X( float   , tfs_z               , 1.00f ,            )  /*  1.0 = disabled \
    */  X( float   , typical_p           , 1.00f ,            )  /*  1.0 = disabled \
    */  X( float   , temp                , 0.80f ,            )  /*  <= 0.0 to sample greedily, 0.0 to not output probabilities \
    */  X( float   , dynatemp_range      , 0.00f ,            )  /*  0.0 = disabled \
    */  X( float   , dynatemp_exponent   , 1.00f ,            )  /*  controls how entropy maps to temperature in dynamic temperature sampler \
    */  X( int32_t , penalty_last_n      , 64    , std::round )  /*  last n tokens to penalize (0 = disable penalty, -1 = context size) \
    */  X( float   , penalty_repeat      , 1.00f ,            )  /*  1.0 = disabled \
    */  X( float   , penalty_freq        , 0.00f ,            )  /*  0.0 = disabled \
    */  X( float   , penalty_present     , 0.00f ,            )  /*  0.0 = disabled \
    */  X( float   , dry_multiplier      , 0.0f  ,            )  /*  0.0 = disabled; DRY repetition penalty for tokens extending repetition: \
    */  X( float   , dry_base            , 1.75f ,            )  /*  0.0 = disabled; multiplier * base ^ (length of sequence before token - allowed length) \
    */  X( int32_t , dry_allowed_length  , 2     , std::round )  /*  tokens extending repetitions beyond this receive penalty \
    */  X( int32_t , dry_penalty_last_n  , -1    , std::round )  /*  how many tokens to scan for repetitions (0 = disable penalty, -1 = context size) \
    */  X( int32_t , mirostat            , 0     , std::round )  /*  0 = disabled, 1 = mirostat, 2 = mirostat 2.0 \
    */  X( float   , mirostat_tau        , 5.00f ,            )  /*  target entropy \
    */  X( float   , mirostat_eta        , 0.10f ,            )  /*  learning rate \
    */  X( float   , xtc_probability     , 0.0f  ,            )  /*  xtc probability \
    */  X( float   , xtc_threshold       , 1.0f  ,            )  /*  xtc threshold, disabled if > 0.5 \
    */  X( float   , top_n_sigma         , 0.0f  ,            )  /*  top-n-sigma \
    */  X( float   , adaptive_target     , -1.0f ,            )  /*  select tokens near this probability (valid range 0.0 to 1.0; <0 = disabled) \
    */  X( float   , adaptive_decay      , 0.90f ,            )  /*  decay rate for target adaptation over time. lower values -> faster but less stable adaptation. (valid range 0.0 to 1.0; ≤0 = no adaptation) \
    */  X( bool    , adaptive_updt_w_cur , false , std::round )  /*  update state with current probability \
    */

enum {
    #undef X
    #define X(T, MEMBER, DV, PRECAST) SPARAMS_ ## MEMBER ## _ENUM,
    X_COMMON_PARAMS_SAMPLING
};

// sampling parameters
typedef struct common_params_sampling {
    #undef X
    #define X(T, MEMBER, DV, _) T MEMBER = DV;
                X_COMMON_PARAMS_SAMPLING
    int32_t     n_prev                = 64;                 // number of previous tokens to remember
    int32_t     n_probs               = 0;                  // if greater than 0, output the probabilities of top n_probs tokens.
    int32_t     total_context_size    = 16840;
    bool        penalize_nl           = false;              // consider newlines as a repeatable token
    uint32_t    seed                  = LLAMA_DEFAULT_SEED; // the seed used to initialize llama_sampling_context

    std::vector<std::string> dry_sequence_breakers = { "\n", ":", "\"", "*" };     // default sequence breakers for DRY

    std::vector<llama_sampler_type> samplers_sequence = {
        llama_sampler_type::DRY,
        llama_sampler_type::TOP_K,
        llama_sampler_type::TFS_Z,
        llama_sampler_type::TYPICAL_P,
        llama_sampler_type::TOP_P,
        llama_sampler_type::MIN_P,
        llama_sampler_type::XTC,
        llama_sampler_type::TOP_N_SIGMA,
        llama_sampler_type::TEMPERATURE,
        llama_sampler_type::ADAPTIVE_P,
        llama_sampler_type::DIST,
    };


    //std::string grammar;  // optional BNF-like grammar to constrain sampling
    common_grammar              grammar;      // optional grammar constraint (user / output-format / tool-calls)
    bool                                grammar_lazy = false;
    std::vector<common_grammar_trigger> grammar_triggers; // optional triggers (for lazy grammars)
    std::set<llama_token>               preserved_tokens;
    // Classifier-Free Guidance
    // https://arxiv.org/abs/2306.17806
    std::string cfg_negative_prompt; // string to help guidance
    float       cfg_scale     = 1.f; // how strong is guidance

    std::unordered_map<llama_token, float> logit_bias; // logit bias for specific tokens

    // The assistant generation prompt already prefilled into the prompt.
    // Fed to the grammar sampler (to advance past pre-existing tokens) and used
    // to determine the reasoning budget sampler's initial state.
    // Only applied when the grammar is of output-format or tool-calls type.
    std::string generation_prompt;

    // reasoning budget sampler parameters
    // these are populated by the server/CLI based on chat template params
    int32_t                  reasoning_budget_tokens = -1;   // -1 = disabled, >= 0 = token budget
    std::vector<llama_token> reasoning_budget_start;           // start tag token sequence
    std::vector<llama_token> reasoning_budget_end;             // end tag token sequence
    std::vector<llama_token> reasoning_budget_forced;          // forced sequence (message + end tag)


    std::vector<llama_token> penalty_prompt_tokens;
    bool                     use_penalty_prompt_tokens = false;

    // expiring logit bias
    struct elb_param {
        struct elb_entry {
            std::vector<size_t>         posi;           // positions of phrases in generated text
            std::vector<float>          addsubs;        // add/modify then subtract/restore sampling parameters
            std::vector<bool>           addflags;       // true if added
            size_t                      max_phrase_len;
            std::vector<std::string>    phrases;
            std::vector<float>          biases;     // for each phrase, nth bias for nth token, extrapolate
            int32_t                     duration;   // bias duration, unless exitword matches
            bool                        is_range;   // has lower and upper biases
            bool operator == (const struct elb_entry& other) const {
                return (is_range == other.is_range)
                    && (duration == other.duration)
                    && (biases == other.biases)
                    && (phrases == other.phrases)
                    && (addflags == other.addflags)
                    && (addsubs == other.addsubs)
                    && (posi == other.posi);
            }
        };
        std::vector<struct elb_entry> entries;
        std::string                   exitword;     // move to next state if matched during generation
        std::string                   op;           // exitword operator
        bool operator == (const struct elb_param& other) const {
            return (op == other.op)
                && (exitword == other.exitword)
                && (entries == other.entries);
        }
    };
    std::vector<struct elb_param> elb_params;

} llama_sampling_params;

// general sampler context
// TODO: move to llama.h
struct common_sampler {
    // parameters that will be used for sampling
    common_params_sampling params;

    // mirostat sampler state
    float mirostat_mu;

    std::string grammar_str;
    std::string grammar_root;

    llama_grammar * grammar;
    llama_sampler * llg = nullptr; // %llguidance requests; not a GBNF grammar

    // TODO: replace with ring-buffer
    std::vector<llama_token>      prev;
    std::vector<llama_token_data> cur;
    llama_sampler_dry* smpl;

    llama_sampler_adaptive_p * adapt_p_ctx;    // adaptive p sampler

    common_reasoning_budget_ctx * rbudget; // reasoning budget sampler

    size_t n_valid; // Number of correct top tokens with correct probabilities.

    // PXA_REP_GUARD_LAZY (2026-10-04; default OFF). The repetition guard (repeat penalty + DRY, auto-armed on loop-prone
    // PXQ1 / PXQN1-heavy files) is a runaway CAP. Always-on it makes every greedy verify a CPU sampler chain and leaves the MTP head drafting the
    // raw argmax against a penalised target. Lazy: `params` carries the REQUEST's own penalty / DRY values while the output is not repeating
    // (pure greedy, argmax-only verify, speculation as without the guard) and the guard's values for guard_hold tokens after an n-gram repeat
    // of guard_k tokens is seen in the generated text. The state lives here (not in params) so a sampler checkpoint / clone carries it.
    bool  guard_lazy   = false;
    float guard_repeat = 1.0f;   // the guard's values (what params carries while hot)
    float guard_dry    = 0.0f;
    float user_repeat  = 1.0f;   // the request's values (what params carries while dormant)
    float user_dry     = 0.0f;
    int   guard_hot    = 0;      // generated tokens left in the hot state
    int   guard_gen    = 0;      // generated tokens accepted so far (the detector reads generated text only)

    llama_token_data_array cur_p; // current candidates

    std::mt19937 rng;

    std::vector<float>* server_biases;

    std::string  drafted_text;
    std::string* to_generated_text = nullptr;

    // expiring logit bias
    struct elb_state {
        struct elb_token {
            int32_t     id;
            float       bias;
            size_t      duration;
            std::string cond;       // bias activation condition
        };
        std::vector<struct elb_token> first_tokens;     // first token of each phrase
        std::vector<struct elb_token> other_tokens;
        std::string                   exitword;
        size_t                        countup;          // compare against duration
        size_t                        delay;            // to avoid early termination of positively biased phrases
        int32_t                       max_cond_len;
        std::string                   jumpword;
        size_t                        jump_idx;
        size_t                        search_word_len;
    };
    std::vector<struct elb_state> elb_states;
    size_t                        elb_idx;          // for elb_states
    size_t                        elb_search_pos;
};



// PXA_TOPK_RAW: counters for the harness. out[0]=fast-path samples taken (mode 1),
// out[1]=shadow compares, out[2]=ties, out[3]=window mismatches, out[4]=genuine mismatches.
void common_sampler_pxa_topk_raw_stats(int64_t out[5]);

// Create a new sampling context instance.
struct common_sampler * common_sampler_init(const struct llama_model * model, const struct common_params_sampling & params);

void common_sampler_free(struct common_sampler * ctx);

// Reset the sampler context
// - clear prev tokens
// - reset grammar
void common_sampler_reset(common_sampler * ctx);

// Review stateful samplers
// - rewind internal states (maybe)
void common_sampler_review(common_sampler * ctx, const size_t n_unsent, const bool rewind_status);

// Set the sampler seed
void llama_sampling_set_rng_seed(struct common_sampler * ctx, uint32_t seed);

// Copy the sampler context
void common_sampler_clone(common_sampler * src, common_sampler * dst);

// Rewind dst to the checkpoint ckpt after a speculative rejection (bug #209). Everything a
// rejected draft may have advanced comes back from the checkpoint (grammar, penalties/prev, DRY,
// adaptive-p history, reasoning budget, mirostat), EXCEPT the random generators -- the sampler's
// own and the adaptive-p sampler's separate one: the verify's random draws are spent.
// Restoring the RNG as well made the next step reuse the same uniforms after every rejection, so
// at temperature > 0 the output stopped sampling the model's distribution.
void common_sampler_rewind_keep_rng(common_sampler * ckpt, common_sampler * dst);

// Get the last sampled token
llama_token llama_sampling_last(common_sampler * ctx);

// Get a string representation of the last sampled tokens
std::string llama_sampling_prev_str(common_sampler * ctx_sampling, llama_context * ctx_main, int n);

// Print sampling parameters into a string
std::string llama_sampling_print(const common_params_sampling & params);

// Print sampling order into a string
std::string llama_sampling_order_print(const common_params_sampling & params);

std::string llama_sampling_type_to_str(llama_sampler_type sampler_type);

std::vector<llama_sampler_type> llama_sampling_types_from_names(const std::vector<std::string> & names, bool allow_alt_names);
std::vector<llama_sampler_type> llama_sampling_types_from_chars(const std::string & names_string);

// this is a common sampling function used across the examples for convenience
// it can serve as a starting point for implementing your own sampling function
// Note: When using multiple sequences, it is the caller's responsibility to call
//       common_sampler_reset when a sequence ends
//
// required:
//  - ctx_main:     context to use for sampling
//  - ctx_sampling: sampling-specific context
//
// optional:
//  - ctx_cfg:      context to use for classifier-free guidance
//  - idx:          sample from llama_get_logits_ith(ctx, idx)
//
// returns:
//  - token:      sampled token
//  - candidates: vector of candidate tokens
//
llama_token common_sampler_sample_legacy(
        struct common_sampler * ctx_sampling,
        struct llama_context * ctx_main,
        struct llama_context * ctx_cfg,
        int idx = -1);

llama_token common_sampler_sample(
    struct common_sampler * ctx_sampling,
    struct llama_context * ctx_main,
    int idx = -1,
    bool grammar_first = false);

// Prepares and adjusts the set of token candidates for sampling based on penalties, biases, and sampling parameters.
llama_token_data_array llama_sampling_prepare(
        struct common_sampler * ctx_sampling,
        struct llama_context * ctx_main,
        struct llama_context * ctx_cfg,
        int idx = 0,
        bool apply_grammar = true,
        std::vector<float> * original_logits = nullptr);

// if is_generated is true, the token is accepted by the sampling chain, the reasoning budget sampler, and the grammar sampler
void common_sampler_accept(
        struct common_sampler * ctx_sampling,
        struct llama_context * ctx_main,
        llama_token id,
        bool is_generated);

// returns at least 1 token, up to draft.size()
// access the internal list of current candidate tokens
llama_token_data_array * common_sampler_get_candidates(struct common_sampler * ctx_sampling, bool do_sort = false);

std::vector<llama_token> llama_sampling_sample_and_accept_n(struct common_sampler * gsmpl, struct llama_context * ctx, const std::vector<llama_token> & draft);

// PXA_SPEC_SAMPLED: `draft_q[i]` is the proposal distribution the drafter DREW draft[i] from, as a
// normalised (id, logit, p) list over its post-filter support. When it is present (and the lever and
// the request allow it) position i is verified with the lossless sampled rule -- accept with
// probability min(1, p/q), otherwise emit a draw from the residual -- instead of by exact match. A
// position with an empty entry (an n-gram stage, say, which proposes tokens with no distribution)
// falls back to exact matching, so a mixed chain stays correct.
//
// Bug #212: `cur_p_out`, when set, receives a copy of the post-chain candidate window of EVERY
// position sampled (one entry per returned token, in order), so a caller reporting post-sampling
// probabilities can give each emitted token its own window instead of the last position's.
// PXA_REP_PREV_v1: the penalty history window (see common_sampler_accept). `keep` is the number of newest
// tokens that must stay visible; push_back + a block trim once the vector passes 2 * keep.
size_t common_sampler_prev_keep(const common_params_sampling & p);
void   common_sampler_prev_push(std::vector<llama_token> & prev, llama_token token, size_t keep);

// PXA_REP_DRY_GREEDY_v1: true when this sampler's DRY stage is armed (multiplier set, base >= 1, a
// window, and DRY is in the request's chain). Temperature 0 used to skip the whole chain after the
// penalty pass, so DRY was a silent no-op there; the greedy draw now applies it before the argmax.
bool common_sampler_dry_active(const struct common_sampler * gsmpl);

// PXA_VERIFY_ARGMAX (2026-09-28): true when this request's draw is the plain argmax of
// the raw logit row -- temp == 0, no grammar, no active penalties, no logit bias / server bias /
// expiring bias, no reasoning budget still able to force, no probabilities asked for -- so a verify can
// be decided from the device-side argmax alone (llama_set_argmax_only).
bool common_sampler_pure_greedy(const struct common_sampler * gsmpl);
// The exact-match verify of common_sampler_sample_and_accept_n for a pure-greedy request whose verify
// decode was argmax-only: same acceptance, same accept() side effects. Empty result = the argmax rows
// are not available (the caller falls back; the decode then copied logits and nothing was consumed).
std::vector<llama_token> common_sampler_accept_n_argmax(struct common_sampler * gsmpl, struct llama_context * ctx,
        const std::vector<int> & idxs, const std::vector<llama_token> & draft);
std::vector<llama_token> common_sampler_sample_and_accept_n(struct common_sampler * gsmpl, struct llama_context * ctx, const std::vector<int> & idxs, const std::vector<llama_token> & draft, bool grammar_first = false,
        const std::vector<std::vector<pxa_spec_cand>> * draft_q = nullptr,
        std::vector<std::vector<llama_token_data>> * cur_p_out = nullptr);

// Greedy argmax sampling for speculative drafting
// PXA_MTP_PMIN_TOPK_v1: the largest top-k window the renormaliser will keep on the stack.
#define COMMON_SAMPLER_PMIN_TOPK_MAX 64

// The argmax's probability renormalised over the k largest logits -- what a `top_k = k`
// sampler chain reports for its first candidate. `max_val` must be the argmax logit.
// k < 2 or k >= n falls back to the full-vocabulary softmax. Exposed for tests/.
float common_sampler_prob_topk_renorm(int n, const float * logits, float max_val, int k);

// PXA_MTP_PMIN_TOPK_v1: `p_min_top_k` selects WHICH probability `out_prob` reports.
//   0 (or >= n_vocab)  the full-vocabulary softmax of the argmax -- the historical quantity
//   k >= 2             the argmax renormalised over the k largest logits
// A confidence floor is only meaningful against the second quantity: on a 248320-token
// vocabulary the full-vocab number has mean 0.036 and clears 0.75 in 0.0 % of draft steps
// (measured 2026-09-08), so a 0.75 floor on it is an off switch, not a filter.
// The top-k form is also cheaper: k exponentials instead of n_vocab.
llama_token common_sampler_sample_speculative(struct common_sampler * gsmpl, struct llama_context * ctx, int idx, float * out_prob = nullptr, int p_min_top_k = 0);

// PXA_MTP_DRAFT_GUARD (default OFF): a temperature-0 request whose repetition guard is armed
// (repeat penalty and/or DRY) verifies against the PENALISED argmax, while the drafter proposes the RAW
// argmax -- so every place the guard bends the answer is a rejected draft (one-card MTP3 on fn32 v1:
// acceptance 64% -> 27%). With the lever on, the draft is the argmax of the draft head's top-W window
// after the request's own repetition penalty (history = the request's prev tail + the drafts already in
// this chain) and its own DRY stage (cloned and fed the chain). Only the PROPOSAL changes: the verify
// is the unchanged exact match against the request's sampler, so the emitted text is byte-identical.
// Returns -1 when the request is not such a request (the caller keeps its argmax path).
bool common_sampler_draft_guard_wanted(const struct common_sampler * gsmpl);
llama_token common_sampler_draft_greedy_guarded(struct common_sampler * gsmpl, struct llama_context * ctx, int idx,
        const std::vector<llama_token> * chain, float * out_prob);

// PXA_SPEC_SAMPLED (default ON since v2026.10): draw the draft token from the draft head's own distribution,
// filtered with this request's sampler parameters, and hand that distribution back in `q_out` so the
// verifier can run the lossless accept/residual rule on it. Returns the drawn token, or -1 when this
// request's sampler chain cannot be mirrored onto the draft head (the caller then keeps its greedy
// draft and the exact rule). `out_prob`, when asked for, is q(drawn token) -- the confidence of the
// token that was actually proposed, which is the quantity a p_min floor means under this rule.
llama_token common_sampler_draft_sample_dist(struct common_sampler * gsmpl, struct llama_context * ctx, int idx,
        std::vector<pxa_spec_cand> & q_out, float * out_prob = nullptr);

// True when the lever is armed AND this request's sampler chain can be mirrored onto the drafter
// (temp > 0, no grammar, no mirostat, no adaptive-p, no dynamic temperature, no DRY, and only
// samplers whose effect on the draft head is reproducible). Refusal is logged once.
bool common_sampler_spec_sampled_ok(const struct common_sampler * gsmpl, struct llama_context * ctx);

// PXA_SPEC_SAMPLED as the sampler resolves it. Read-only; for the startup banner and ledgers.
bool common_sampler_spec_sampled_active();

// PXA_SPEC_BLOCK_VERIFY (default off) as the sampler resolves it (PXA_SPEC_SAMPLED and the block switch both on):
// a sampled draft of two or more tokens is accepted jointly. Read-only; for the startup banner.
bool common_sampler_spec_block_verify_active();

// PXA_SPEC_RELAXED as the sampler resolves it (env, else the config level): true means a draft
// token inside the target's post-filter candidate set with p >= pmin is kept at temp>0 instead of
// the target's own sample. Exact-match semantics always hold at temp<=0. Read-only; for ledgers.
bool  common_sampler_spec_relaxed_active();
float common_sampler_spec_relaxed_pmin();

// PXA_SPEC_ACCEPT_RULE_v1: the ONE place that answers "does this request's speculative
// verification behave as exact match?". common_sampler_sample_and_accept_n and every caller that
// reports or plans for the rule must go through this, so the reported rule and the executed rule
// cannot drift apart. `why`, when given, is filled with a short public-safe reason.
// Returns false when the request can keep a draft token the target did not sample.
bool common_sampler_acceptance_is_exact(const struct common_params_sampling & params, const char ** why = nullptr);

void common_expiring_logit_bias_apply(struct common_sampler* ctx_sampling, float* logits);

void common_expiring_logit_bias_accept(struct common_sampler* ctx_sampling, struct llama_context * ctx_main);

llama_sampler * llama_sampler_init_llg(const llama_vocab * vocab,
    const char * grammar_kind, const char * grammar_data);
